In [132]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD, Adam
from keras.callbacks import EarlyStopping
from keras.utils import to_categorical
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, log_loss

In [133]:
df = pd.read_csv('fetal_health.csv')
df

baseline value  accelerations  fetal_movement  uterine_contractions  \
0              120.0          0.000           0.000                 0.000   
1              132.0          0.006           0.000                 0.006   
2              133.0          0.003           0.000                 0.008   
3              134.0          0.003           0.000                 0.008   
4              132.0          0.007           0.000                 0.008   
...              ...            ...             ...                   ...   
2121           140.0          0.000           0.000                 0.007   
2122           140.0          0.001           0.000                 0.007   
2123           140.0          0.001           0.000                 0.007   
2124           140.0          0.001           0.000                 0.006   
2125           142.0          0.002           0.002                 0.008   

      light_decelerations  severe_decelerations  prolongued_decelerations  \
0                   0.000                   0.0                       0.0   
1                   0.003                   0.0                       0.0   
2                   0.003                   0.0                       0.0   
3                   0.003                   0.0                       0.0   
4                   0.000                   0.0                       0.0   
...                   ...                   ...                       ...   
2121                0.000                   0.0                       0.0   
2122                0.000                   0.0                       0.0   
2123                0.000                   0.0                       0.0   
2124                0.000                   0.0                       0.0   
2125                0.000                   0.0                       0.0   

      abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                                73.0                                   0.5   
1                                17.0                                   2.1   
2                                16.0                                   2.1   
3                                16.0                                   2.4   
4                                16.0                                   2.4   
...                               ...                                   ...   
2121                             79.0                                   0.2   
2122                             78.0                                   0.4   
2123                             79.0                                   0.4   
2124                             78.0                                   0.4   
2125                             74.0                                   0.4   

      percentage_of_time_with_abnormal_long_term_variability  ...  \
0                                                  43.0       ...   
1                                                   0.0       ...   
2                                                   0.0       ...   
3                                                   0.0       ...   
4                                                   0.0       ...   
...                                                 ...       ...   
2121                                               25.0       ...   
2122                                               22.0       ...   
2123                                               20.0       ...   
2124                                               27.0       ...   
2125                                               36.0       ...   

      histogram_min  histogram_max  histogram_number_of_peaks  \
0              62.0          126.0                        2.0   
1              68.0          198.0                        6.0   
2              68.0          198.0                        5.0   
3              53.0          170.0                       11.0   
4              53.0          170.0                   

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2126 entries, 0 to 2125
Data columns (total 22 columns):
 #   Column                                                  Non-Null Count  Dtype  
---  ------                                                  --------------  -----  
 0   baseline value                                          2126 non-null   float64
 1   accelerations                                           2126 non-null   float64
 2   fetal_movement                                          2126 non-null   float64
 3   uterine_contractions                                    2126 non-null   float64
 4   light_decelerations                                     2126 non-null   float64
 5   severe_decelerations                                    2126 non-null   float64
 6   prolongued_decelerations                                2126 non-null   float64
 7   abnormal_short_term_variability                         2126 non-null   float64
 8   mean_value_of_short_term_variability  

In [135]:
df['fetal_health'].unique()

array([2., 1., 3.])

In [136]:
X = df.drop('fetal_health', axis=1)
X

baseline value  accelerations  fetal_movement  uterine_contractions  \
0              120.0          0.000           0.000                 0.000   
1              132.0          0.006           0.000                 0.006   
2              133.0          0.003           0.000                 0.008   
3              134.0          0.003           0.000                 0.008   
4              132.0          0.007           0.000                 0.008   
...              ...            ...             ...                   ...   
2121           140.0          0.000           0.000                 0.007   
2122           140.0          0.001           0.000                 0.007   
2123           140.0          0.001           0.000                 0.007   
2124           140.0          0.001           0.000                 0.006   
2125           142.0          0.002           0.002                 0.008   

      light_decelerations  severe_decelerations  prolongued_decelerations  \
0                   0.000                   0.0                       0.0   
1                   0.003                   0.0                       0.0   
2                   0.003                   0.0                       0.0   
3                   0.003                   0.0                       0.0   
4                   0.000                   0.0                       0.0   
...                   ...                   ...                       ...   
2121                0.000                   0.0                       0.0   
2122                0.000                   0.0                       0.0   
2123                0.000                   0.0                       0.0   
2124                0.000                   0.0                       0.0   
2125                0.000                   0.0                       0.0   

      abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                                73.0                                   0.5   
1                                17.0                                   2.1   
2                                16.0                                   2.1   
3                                16.0                                   2.4   
4                                16.0                                   2.4   
...                               ...                                   ...   
2121                             79.0                                   0.2   
2122                             78.0                                   0.4   
2123                             79.0                                   0.4   
2124                             78.0                                   0.4   
2125                             74.0                                   0.4   

      percentage_of_time_with_abnormal_long_term_variability  ...  \
0                                                  43.0       ...   
1                                                   0.0       ...   
2                                                   0.0       ...   
3                                                   0.0       ...   
4                                                   0.0       ...   
...                                                 ...       ...   
2121                                               25.0       ...   
2122                                               22.0       ...   
2123                                               20.0       ...   
2124                                               27.0       ...   
2125                                               36.0       ...   

      histogram_width  histogram_min  histogram_max  \
0                64.0           62.0          126.0   
1               130.0           68.0          198.0   
2               130.0           68.0          198.0   
3               117.0           53.0          170.0   
4               117.0           53.0          170.0   
...               ...            ...            

In [137]:
target_name = df['fetal_health'].unique()
target_name

array([2., 1., 3.])

In [138]:
target_dict = {n:i for i, n in enumerate(target_name)}
target_dict

{2.0: 0, 1.0: 1, 3.0: 2}

In [139]:
y = df['fetal_health'].map(target_dict)
y

0       0
1       1
2       1
3       1
4       1
       ..
2121    0
2122    0
2123    0
2124    0
2125    1
Name: fetal_health, Length: 2126, dtype: int64

In [140]:
y_cat = to_categorical(y, dtype=int)
y_cat

array([[1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       ...,
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [141]:
X_train, X_test, y_train, y_test = train_test_split(X, y_cat, test_size=0.2, random_state=1)

In [142]:
model = Sequential()
model.add(Dense(64, input_shape = (21,), activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(optimizer='adam', loss ='categorical_crossentropy', metrics = ['accuracy'])
model.summary()

Model: "sequential_18"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_52 (Dense)            (None, 64)                1408      
                                                                 
 dense_53 (Dense)            (None, 64)                4160      
                                                                 
 dense_54 (Dense)            (None, 32)                2080      
                                                                 
 dense_55 (Dense)            (None, 3)                 99        
                                                                 
Total params: 7,747
Trainable params: 7,747
Non-trainable params: 0
_________________________________________________________________


In [143]:
earlyStop = EarlyStopping(monitor='loss', patience=10, verbose=1)

In [144]:
model.fit(X_train, y_train, epochs=100, callbacks=earlyStop, verbose=1, validation_split=0.1)

Epoch 1/100
48/48 [==============================] - 1s 4ms/step - loss: 1.3378 - accuracy: 0.7569 - val_loss: 0.4613 - val_accuracy: 0.8765
Epoch 2/100
48/48 [==============================] - 0s 2ms/step - loss: 0.7658 - accuracy: 0.7935 - val_loss: 0.5828 - val_accuracy: 0.8294
Epoch 3/100
48/48 [==============================] - 0s 2ms/step - loss: 0.5364 - accuracy: 0.8111 - val_loss: 0.4075 - val_accuracy: 0.8471
Epoch 4/100
48/48 [==============================] - 0s 3ms/step - loss: 0.4989 - accuracy: 0.8359 - val_loss: 0.3278 - val_accuracy: 0.9000
Epoch 5/100
48/48 [==============================] - 0s 2ms/step - loss: 0.4297 - accuracy: 0.8523 - val_loss: 0.3340 - val_accuracy: 0.8824
Epoch 6/100
48/48 [==============================] - 0s 2ms/step - loss: 0.5604 - accuracy: 0.8190 - val_loss: 0.3416 - val_accuracy: 0.8824
Epoch 7/100
48/48 [==============================] - 0s 2ms/step - loss: 0.4262 - accuracy: 0.8556 - val_loss: 0.3519 - val_accuracy: 0.8529
Epoch 8/100
4

In [145]:
y_pred = model.predict(X_test)
y_pred

14/14 [==============================] - 0s 1ms/step


array([[1.5332051e-01, 8.4609473e-01, 5.8476371e-04],
       [8.8046694e-01, 1.1810191e-01, 1.4311881e-03],
       [1.7399184e-01, 8.2552069e-01, 4.8742822e-04],
       ...,
       [1.5070832e-01, 8.4831870e-01, 9.7293564e-04],
       [3.0013362e-01, 6.8147016e-01, 1.8396225e-02],
       [6.3103896e-01, 4.6616614e-02, 3.2234445e-01]], dtype=float32)

In [146]:
y_pred_class = np.argmax(y_pred, axis=1)
y_test_class = np.argmax(y_test, axis=1)

In [147]:
print(classification_report(y_test_class, y_pred_class));

              precision    recall  f1-score   support

           0       0.65      0.66      0.66        68
           1       0.93      0.92      0.93       326
           2       0.73      0.84      0.78        32

    accuracy                           0.87       426
   macro avg       0.77      0.81      0.79       426
weighted avg       0.87      0.87      0.87       426



In [148]:
confusion_matrix(y_test_class, y_pred_class)

array([[ 45,  17,   6],
       [ 23, 299,   4],
       [  1,   4,  27]], dtype=int64)

In [149]:
log_loss(y_test_class, y_pred)

0.29689735596252936

In [150]:
loss, accuracy = model.evaluate(X_test, y_test)
print("Loss: " + str(loss))
print("Accuracy: " + str(accuracy))

14/14 [==============================] - 0s 1ms/step - loss: 0.2969 - accuracy: 0.8709
Loss: 0.29689735174179077
Accuracy: 0.8708920478820801
